{% set name = "distromax" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2d00025355d7559d2fdb2d022a564ed246d7364c867483010dde4080cb644274

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy
    - scipy
    - scikit-image
    - tqdm

test:
  imports:
    - distromax

about:
  home: https://github.com/Rodrigo-Tenorio/distromax/
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Empirically estimate the distribution of the loudest candidate from a gravitational-wave search
  description: |
    This is a python package implementing a method to empirically estimate 
    the distribution of the loudest candidate from a generic gravitational-wave search
    using results from extreme value theory.
  dev_url: https://github.com/Rodrigo-Tenorio/distromax/

extra:
  recipe-maintainers:
    - Rodrigo-Tenorio
