{% set name = "distromax" %}
{% set version = "1.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 92718c9313f77314d986077992186c2bf71639e3890b48bbbd0dddc5e326cde3

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - scikit-image
    - tqdm

test:
  requires:
    - python {{ python_min }}
  imports:
    - distromax

about:
  home: https://github.com/Rodrigo-Tenorio/distromax/
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Empirically estimate the distribution of the loudest candidate from a gravitational-wave search
  description: |
    This is a python package implementing a method to empirically estimate 
    the distribution of the loudest candidate from a generic gravitational-wave search
    using results from extreme value theory.
  dev_url: https://github.com/Rodrigo-Tenorio/distromax/

extra:
  recipe-maintainers:
    - Rodrigo-Tenorio
