{% set name = "distromax" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f215a2df756ba048ec93df9d844cd89c62c32ad8b0405ae9a2d02f12a7c8a600

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - scikit-image
    - tqdm

test:
  requires:
    - python {{ python_min }}
  imports:
    - distromax

about:
  home: https://github.com/Rodrigo-Tenorio/distromax/
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Empirically estimate the distribution of the loudest candidate from a gravitational-wave search
  description: |
    This is a python package implementing a method to empirically estimate 
    the distribution of the loudest candidate from a generic gravitational-wave search
    using results from extreme value theory.
  dev_url: https://github.com/Rodrigo-Tenorio/distromax/ 

extra:
  recipe-maintainers:
    - Rodrigo-Tenorio
